# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.25.1/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.25.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/balazs/Developer/Git/personal/opengl-engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/balazs/Developer/Git/personal/opengl-engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.25.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.25.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/balazs/Developer/Git/personal/opengl-engine/CMakeFiles /Users/balazs/Developer/Git/personal/opengl-engine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/balazs/Developer/Git/personal/opengl-engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hyper

# Build rule for target.
hyper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hyper
.PHONY : hyper

# fast build rule for target.
hyper/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/build
.PHONY : hyper/fast

src/cpp/App.o: src/cpp/App.cpp.o
.PHONY : src/cpp/App.o

# target to build an object file
src/cpp/App.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/App.cpp.o
.PHONY : src/cpp/App.cpp.o

src/cpp/App.i: src/cpp/App.cpp.i
.PHONY : src/cpp/App.i

# target to preprocess a source file
src/cpp/App.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/App.cpp.i
.PHONY : src/cpp/App.cpp.i

src/cpp/App.s: src/cpp/App.cpp.s
.PHONY : src/cpp/App.s

# target to generate assembly for a file
src/cpp/App.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/App.cpp.s
.PHONY : src/cpp/App.cpp.s

src/cpp/Camera.o: src/cpp/Camera.cpp.o
.PHONY : src/cpp/Camera.o

# target to build an object file
src/cpp/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Camera.cpp.o
.PHONY : src/cpp/Camera.cpp.o

src/cpp/Camera.i: src/cpp/Camera.cpp.i
.PHONY : src/cpp/Camera.i

# target to preprocess a source file
src/cpp/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Camera.cpp.i
.PHONY : src/cpp/Camera.cpp.i

src/cpp/Camera.s: src/cpp/Camera.cpp.s
.PHONY : src/cpp/Camera.s

# target to generate assembly for a file
src/cpp/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Camera.cpp.s
.PHONY : src/cpp/Camera.cpp.s

src/cpp/Display.o: src/cpp/Display.cpp.o
.PHONY : src/cpp/Display.o

# target to build an object file
src/cpp/Display.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Display.cpp.o
.PHONY : src/cpp/Display.cpp.o

src/cpp/Display.i: src/cpp/Display.cpp.i
.PHONY : src/cpp/Display.i

# target to preprocess a source file
src/cpp/Display.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Display.cpp.i
.PHONY : src/cpp/Display.cpp.i

src/cpp/Display.s: src/cpp/Display.cpp.s
.PHONY : src/cpp/Display.s

# target to generate assembly for a file
src/cpp/Display.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Display.cpp.s
.PHONY : src/cpp/Display.cpp.s

src/cpp/Framebuffer.o: src/cpp/Framebuffer.cpp.o
.PHONY : src/cpp/Framebuffer.o

# target to build an object file
src/cpp/Framebuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Framebuffer.cpp.o
.PHONY : src/cpp/Framebuffer.cpp.o

src/cpp/Framebuffer.i: src/cpp/Framebuffer.cpp.i
.PHONY : src/cpp/Framebuffer.i

# target to preprocess a source file
src/cpp/Framebuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Framebuffer.cpp.i
.PHONY : src/cpp/Framebuffer.cpp.i

src/cpp/Framebuffer.s: src/cpp/Framebuffer.cpp.s
.PHONY : src/cpp/Framebuffer.s

# target to generate assembly for a file
src/cpp/Framebuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Framebuffer.cpp.s
.PHONY : src/cpp/Framebuffer.cpp.s

src/cpp/GLSLProgram.o: src/cpp/GLSLProgram.cpp.o
.PHONY : src/cpp/GLSLProgram.o

# target to build an object file
src/cpp/GLSLProgram.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/GLSLProgram.cpp.o
.PHONY : src/cpp/GLSLProgram.cpp.o

src/cpp/GLSLProgram.i: src/cpp/GLSLProgram.cpp.i
.PHONY : src/cpp/GLSLProgram.i

# target to preprocess a source file
src/cpp/GLSLProgram.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/GLSLProgram.cpp.i
.PHONY : src/cpp/GLSLProgram.cpp.i

src/cpp/GLSLProgram.s: src/cpp/GLSLProgram.cpp.s
.PHONY : src/cpp/GLSLProgram.s

# target to generate assembly for a file
src/cpp/GLSLProgram.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/GLSLProgram.cpp.s
.PHONY : src/cpp/GLSLProgram.cpp.s

src/cpp/Keyboard.o: src/cpp/Keyboard.cpp.o
.PHONY : src/cpp/Keyboard.o

# target to build an object file
src/cpp/Keyboard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Keyboard.cpp.o
.PHONY : src/cpp/Keyboard.cpp.o

src/cpp/Keyboard.i: src/cpp/Keyboard.cpp.i
.PHONY : src/cpp/Keyboard.i

# target to preprocess a source file
src/cpp/Keyboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Keyboard.cpp.i
.PHONY : src/cpp/Keyboard.cpp.i

src/cpp/Keyboard.s: src/cpp/Keyboard.cpp.s
.PHONY : src/cpp/Keyboard.s

# target to generate assembly for a file
src/cpp/Keyboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Keyboard.cpp.s
.PHONY : src/cpp/Keyboard.cpp.s

src/cpp/Light.o: src/cpp/Light.cpp.o
.PHONY : src/cpp/Light.o

# target to build an object file
src/cpp/Light.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Light.cpp.o
.PHONY : src/cpp/Light.cpp.o

src/cpp/Light.i: src/cpp/Light.cpp.i
.PHONY : src/cpp/Light.i

# target to preprocess a source file
src/cpp/Light.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Light.cpp.i
.PHONY : src/cpp/Light.cpp.i

src/cpp/Light.s: src/cpp/Light.cpp.s
.PHONY : src/cpp/Light.s

# target to generate assembly for a file
src/cpp/Light.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Light.cpp.s
.PHONY : src/cpp/Light.cpp.s

src/cpp/Mesh.o: src/cpp/Mesh.cpp.o
.PHONY : src/cpp/Mesh.o

# target to build an object file
src/cpp/Mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Mesh.cpp.o
.PHONY : src/cpp/Mesh.cpp.o

src/cpp/Mesh.i: src/cpp/Mesh.cpp.i
.PHONY : src/cpp/Mesh.i

# target to preprocess a source file
src/cpp/Mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Mesh.cpp.i
.PHONY : src/cpp/Mesh.cpp.i

src/cpp/Mesh.s: src/cpp/Mesh.cpp.s
.PHONY : src/cpp/Mesh.s

# target to generate assembly for a file
src/cpp/Mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Mesh.cpp.s
.PHONY : src/cpp/Mesh.cpp.s

src/cpp/Model.o: src/cpp/Model.cpp.o
.PHONY : src/cpp/Model.o

# target to build an object file
src/cpp/Model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Model.cpp.o
.PHONY : src/cpp/Model.cpp.o

src/cpp/Model.i: src/cpp/Model.cpp.i
.PHONY : src/cpp/Model.i

# target to preprocess a source file
src/cpp/Model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Model.cpp.i
.PHONY : src/cpp/Model.cpp.i

src/cpp/Model.s: src/cpp/Model.cpp.s
.PHONY : src/cpp/Model.s

# target to generate assembly for a file
src/cpp/Model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Model.cpp.s
.PHONY : src/cpp/Model.cpp.s

src/cpp/OBJLoader.o: src/cpp/OBJLoader.cpp.o
.PHONY : src/cpp/OBJLoader.o

# target to build an object file
src/cpp/OBJLoader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/OBJLoader.cpp.o
.PHONY : src/cpp/OBJLoader.cpp.o

src/cpp/OBJLoader.i: src/cpp/OBJLoader.cpp.i
.PHONY : src/cpp/OBJLoader.i

# target to preprocess a source file
src/cpp/OBJLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/OBJLoader.cpp.i
.PHONY : src/cpp/OBJLoader.cpp.i

src/cpp/OBJLoader.s: src/cpp/OBJLoader.cpp.s
.PHONY : src/cpp/OBJLoader.s

# target to generate assembly for a file
src/cpp/OBJLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/OBJLoader.cpp.s
.PHONY : src/cpp/OBJLoader.cpp.s

src/cpp/Program.o: src/cpp/Program.cpp.o
.PHONY : src/cpp/Program.o

# target to build an object file
src/cpp/Program.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Program.cpp.o
.PHONY : src/cpp/Program.cpp.o

src/cpp/Program.i: src/cpp/Program.cpp.i
.PHONY : src/cpp/Program.i

# target to preprocess a source file
src/cpp/Program.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Program.cpp.i
.PHONY : src/cpp/Program.cpp.i

src/cpp/Program.s: src/cpp/Program.cpp.s
.PHONY : src/cpp/Program.s

# target to generate assembly for a file
src/cpp/Program.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Program.cpp.s
.PHONY : src/cpp/Program.cpp.s

src/cpp/Scene.o: src/cpp/Scene.cpp.o
.PHONY : src/cpp/Scene.o

# target to build an object file
src/cpp/Scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Scene.cpp.o
.PHONY : src/cpp/Scene.cpp.o

src/cpp/Scene.i: src/cpp/Scene.cpp.i
.PHONY : src/cpp/Scene.i

# target to preprocess a source file
src/cpp/Scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Scene.cpp.i
.PHONY : src/cpp/Scene.cpp.i

src/cpp/Scene.s: src/cpp/Scene.cpp.s
.PHONY : src/cpp/Scene.s

# target to generate assembly for a file
src/cpp/Scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Scene.cpp.s
.PHONY : src/cpp/Scene.cpp.s

src/cpp/Texture.o: src/cpp/Texture.cpp.o
.PHONY : src/cpp/Texture.o

# target to build an object file
src/cpp/Texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Texture.cpp.o
.PHONY : src/cpp/Texture.cpp.o

src/cpp/Texture.i: src/cpp/Texture.cpp.i
.PHONY : src/cpp/Texture.i

# target to preprocess a source file
src/cpp/Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Texture.cpp.i
.PHONY : src/cpp/Texture.cpp.i

src/cpp/Texture.s: src/cpp/Texture.cpp.s
.PHONY : src/cpp/Texture.s

# target to generate assembly for a file
src/cpp/Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Texture.cpp.s
.PHONY : src/cpp/Texture.cpp.s

src/cpp/Window.o: src/cpp/Window.cpp.o
.PHONY : src/cpp/Window.o

# target to build an object file
src/cpp/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Window.cpp.o
.PHONY : src/cpp/Window.cpp.o

src/cpp/Window.i: src/cpp/Window.cpp.i
.PHONY : src/cpp/Window.i

# target to preprocess a source file
src/cpp/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Window.cpp.i
.PHONY : src/cpp/Window.cpp.i

src/cpp/Window.s: src/cpp/Window.cpp.s
.PHONY : src/cpp/Window.s

# target to generate assembly for a file
src/cpp/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hyper.dir/build.make CMakeFiles/hyper.dir/src/cpp/Window.cpp.s
.PHONY : src/cpp/Window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... hyper"
	@echo "... src/cpp/App.o"
	@echo "... src/cpp/App.i"
	@echo "... src/cpp/App.s"
	@echo "... src/cpp/Camera.o"
	@echo "... src/cpp/Camera.i"
	@echo "... src/cpp/Camera.s"
	@echo "... src/cpp/Display.o"
	@echo "... src/cpp/Display.i"
	@echo "... src/cpp/Display.s"
	@echo "... src/cpp/Framebuffer.o"
	@echo "... src/cpp/Framebuffer.i"
	@echo "... src/cpp/Framebuffer.s"
	@echo "... src/cpp/GLSLProgram.o"
	@echo "... src/cpp/GLSLProgram.i"
	@echo "... src/cpp/GLSLProgram.s"
	@echo "... src/cpp/Keyboard.o"
	@echo "... src/cpp/Keyboard.i"
	@echo "... src/cpp/Keyboard.s"
	@echo "... src/cpp/Light.o"
	@echo "... src/cpp/Light.i"
	@echo "... src/cpp/Light.s"
	@echo "... src/cpp/Mesh.o"
	@echo "... src/cpp/Mesh.i"
	@echo "... src/cpp/Mesh.s"
	@echo "... src/cpp/Model.o"
	@echo "... src/cpp/Model.i"
	@echo "... src/cpp/Model.s"
	@echo "... src/cpp/OBJLoader.o"
	@echo "... src/cpp/OBJLoader.i"
	@echo "... src/cpp/OBJLoader.s"
	@echo "... src/cpp/Program.o"
	@echo "... src/cpp/Program.i"
	@echo "... src/cpp/Program.s"
	@echo "... src/cpp/Scene.o"
	@echo "... src/cpp/Scene.i"
	@echo "... src/cpp/Scene.s"
	@echo "... src/cpp/Texture.o"
	@echo "... src/cpp/Texture.i"
	@echo "... src/cpp/Texture.s"
	@echo "... src/cpp/Window.o"
	@echo "... src/cpp/Window.i"
	@echo "... src/cpp/Window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

