#pragma once

#include <GL/glew.h>

const GLuint DEFAULT_WINDOW_WIDTH = 800, DEFAULT_WINDOW_HEIGHT = 800;
const char *WINDOW_TITLE = "OpenGL Application";

float PIXEL_RATIO = 1.5;
int FRAMEBUFFER_DIMENSIONS = DEFAULT_WINDOW_HEIGHT / PIXEL_RATIO;
